#!/bin/sh -e
# -*- coding: utf-8; mode: sh -*-
CONTAINER=tvaughan/node
VERSION=5.3.0
ENTRYPOINT=/opt/node/bin/$(basename $0)
docker run --rm -i -t -v $PWD:/tmp/workdir -w /tmp/workdir --entrypoint=$ENTRYPOINT $CONTAINER:$VERSION "$@"
exit 0
